ShareYun/ShareYunSourse/Models/Account/LoginModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ShareYunSourse.Web.Models.Account
{
    public class LoginModel
    {
        [Required]
        public string UserName { get; set; }
        [Required]
        public string UserPwd { get; set; }
        public int? IsDeprt { get; set; }

        public string VerCode { get; set; }

    }
}

ShareYun/ShareYunSourse/Models/Account/LoginResultModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ShareYunSourse.Web.Models.Account
{
    public class LoginResultModel
    {
        public string Error { get; set; }
        public string SuccInfo { get; set; }
        public string ReturnUrl { get; set; }

    }
}

ShareYun/ShareYunSourse/Models/ErrorViewModel.cs
using System;

namespace ShareYunSourse.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ShareYun/ShareYunSourse/Components/HeaderViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using ShareYunSourse.Application;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ShareYunSourse.Web.Components
{
    public class HeaderViewComponent: ViewComponent
    {
        private readonly IUserManager _userManager;
        public HeaderViewComponent(IUserManager userManager)
        {
            _userManager = userManager;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var user=await  _userManager.GetCurrUser();
            return View(user);
        }
    }
}

ShareYun/ShareYunSourse/Components/SidebarViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ShareYunSourse.Web.Components
{
    public class SidebarViewComponent: ViewComponent
    {
        public SidebarViewComponent() { }
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

ShareYun/ShareYunSourse/Controllers/AccountController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ShareYunSourse.Web.Models.Account;
using ShareYunSourse.Application;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using System.Security.Claims;
using System;

namespace ShareYunSourse.Web.Controllers
{
    public class AccountController : Controller
    {
        private readonly IUserManager _userManager;
        public AccountController(IUserManager userManager)
        {
            _userManager = userManager;
        }
        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Login(LoginModel input)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.GetUserByUserNameAndPwd(input.UserName, input.UserPwd);
                 if (user == null) { return Json(new LoginResultModel { Error = "用户名或密码错误" }); }
                await _userManager.SignSession(user);
                return Json(new LoginResultModel { SuccInfo = "登录成功",ReturnUrl="/Home/Index" });
            }
            else { return Json(new LoginResultModel { Error = "用户名或密码错误" }); }
        }
    }
}

ShareYun/ShareYunSourse/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using ShareYunSourse.Models;
using ShareYunSourse.Application;
using ShareYunSourse.Web.Controllers;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authentication;
using System.Threading.Tasks;
using System.Security.Claims;
using System.Linq;
using ShareYunSourse.Application.Dto;
using ShareYunSourse.Web.Filter;
using System;
using ShareYunSourse.Application.Users.Dto;

namespace ShareYunSourse.Controllers
{
    [UserFilter]
    public class HomeController : Controller
    {
        private readonly IUserManager _userManager;
        public HomeController(IUserManager  userManager)
        {
            _userManager = userManager;
        }
     
        public async Task<IActionResult> Index()
        {
            return View();
        }
   
        public async Task<JsonResult> GetUsersAsync(GetUserInput input)
        {
            var users= await _userManager.GetUsers(input);
            return Json(users); 
        }
        [HttpGet]
        public async Task<IActionResult> ViewUser(int id)
        {
            var users = await _userManager.GetUserById(id);
            return Json(users);
        }

        public async Task  EditOrCreateUser(UserDto input)
        {         
            await _userManager.EditOrCreateUserById(input);         
        }
        public async Task DeleteUserById(int id)
        {
            await _userManager.DeleteUserById(id);
        }

        public async Task<IActionResult> Test()
        {
            await _userManager.TestAsync();
            return Json("s");
        }
    }
}

ShareYun/ShareYunSourse/Controllers/LayoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace ShareYunSourse.Web.Controllers
{
    public class LayoutController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ShareYun/ShareYunSourse/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

ShareYun/ShareYunSourse/Views/Home/Index.cshtml
<div class="panel-body" style="padding-bottom:0px;">
    <div class="panel panel-default">
        <div class="panel-heading">用户管理</div>
        <div class="panel-body">
            <form id="formSearch" class="form-horizontal">
                <div class="form-group" style="margin-top:15px">
                    <label class="control-label col-sm-1" for="search_userName">用户名</label>
                    <div class="col-sm-3">
                        <input type="text" class="form-control" id="search_userName">
                    </div>
                    <label class="control-label col-sm-1" for="search_email">邮箱</label>
                    <div class="col-sm-3">
                        <input type="text" class="form-control" id="search_email">
                    </div>
                    <div class="col-sm-4" style="text-align:left;">
                        <button type="button" style="margin-left:50px" id="btn_query" class="btn btn-primary">查询</button>
                        <button type="button" style="margin-left:50px" id="btn_add" class="btn btn-primary">新增</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div id="toolbar" class="btn-group">
        <button id="btn_add" type="button" class="btn btn-default">
            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>新增
        </button>
        <button id="btn_edit" type="button" class="btn btn-default">
            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>修改
        </button>
        <button id="btn_delete" type="button" class="btn btn-default">
            <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>删除
        </button>
    </div>
    <table id="tb_departments"></table>
</div>
@Html.Partial("ViewUser")
@section Scripts {
<script src="~/StaticFile/Home/Index.js"></script>
}

ShareYun/ShareYunSourse/Views/Home/ViewUser.cshtml
<div class="modal" id="myModal" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="title"></h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal" role="form" id="myform" action="/Home/EditOrCreateUser">
                    <input type="text" class="form-control hidden" id="id" name="id">
                    <div class="form-group">
                        <label for="userName" class="col-sm-2 control-label">用户名：</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control" id="userName" name="userName">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="email" class="col-sm-2 control-label">邮箱：</label>
                        <div class="col-sm-8">
                            <input type="email" class="form-control" id="email" name="email">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="age" class="col-sm-2 control-label">年龄：</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control" id="age" name="age" />
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                        <button type="submit" id="saveData" class="btn btn-primary">保存</button>
                    </div>
                </form>
            </div>

        </div>
    </div>
</div>

ShareYun/ShareYunSourse/Views/Shared/Components/Header/Default.cshtml
@model ShareYunSourse.User
<div class="header">
    <div class="container">
        <div class="row">
            <div class="col-md-5">
                <!-- Logo -->
                <div class="logo">
                    <h1><a href="/home/index">.netCore 2.0 AutoFac</a></h1>
                </div>
            </div>
            <div class="col-md-5">
                <div class="row">
                    <div class="col-lg-12">
                    </div>
                </div>
            </div>
            <div class="col-md-2">
                <div class="navbar navbar-inverse" role="banner">
                    <nav class="collapse navbar-collapse bs-navbar-collapse navbar-right" role="navigation">
                        <ul class="nav navbar-nav">
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">@Model.UserName <b class="caret"></b></a>
                                <ul class="dropdown-menu animated fadeInUp">
                                    <li><a href="profile.html">Profile</a></li>
                                    <li><a href="login.html">Logout</a></li>
                                </ul>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</div>

ShareYun/ShareYunSourse/Views/Shared/Components/Sidebar/Default.cshtml
<div class="col-md-2">
    <div class="sidebar content-box" style="display: block;">

        <ul class="nav">

            <!-- Main menu -->
            <li class="current"><a href="/home/index"><i class="glyphicon glyphicon-home"></i> 首页</a></li>
            <li><a href="calendar.html"><i class="glyphicon glyphicon-calendar"></i> Calendar</a></li>
            <li><a href="stats.html"><i class="glyphicon glyphicon-stats"></i> Statistics (Charts)</a></li>
            <li><a href="tables.html"><i class="glyphicon glyphicon-list"></i> Tables</a></li>
            <li><a href="buttons.html"><i class="glyphicon glyphicon-record"></i> Buttons</a></li>
            <li><a href="editors.html"><i class="glyphicon glyphicon-pencil"></i> Editors</a></li>
            <li><a href="forms.html"><i class="glyphicon glyphicon-tasks"></i> Forms</a></li>
            <li class="submenu">
                <a href="#">
                    <i class="glyphicon glyphicon-list"></i> Pages
                    <span class="caret pull-right"></span>
                </a>
                <!-- Sub menu -->
                <ul>
                    <li><a href="login.html">Login</a></li>
                    <li><a href="signup.html">Signup</a></li>
                </ul>
            </li>
        </ul>

    </div>
</div>

ShareYun/ShareYunSourse/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Bootstrap Admin Theme v3</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <!-- styles -->
    <link href="~/css/styles.css" rel="stylesheet" />
    <link href="~/lib/bootstrap-table/bootstrap-table.min.css" rel="stylesheet" />
    @section Styles{ @RenderSection("Styles", required: false)}
</head>
<body>
    @await Component.InvokeAsync("Header")
    <div class="page-content">
        <div class="row">
            @await Component.InvokeAsync("Sidebar")
            <div class="col-md-10">
                <div class="row">
                    <div class="col-md-12">
                        @RenderBody()
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    @*<script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>*@
    <script src="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="~/js/custom.js"></script>
    <script src="~/lib/bootstrap-table/bootstrap-table.min.js"></script>
    <script src="~/lib/bootstrap-table/bootstrap-table-zh-CN.min.js"></script>
    <script src="~/lib/moment/moment.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/sweetalert/sweetalert.min.js"></script>
    <script src="~/lib/bootstrap-notify/bootstrap-notify.min.js"></script>
    @RenderSection("Scripts", required:false)
</body>
</html>